<?php

use Illuminate\Database\Seeder;

class GamesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
$sql = '
INSERT INTO games(id, name, description, msrp, minimumPlayers, maximumPlayers, recommendedAge, categoryId, avgGameLength) VALUES ("1","Chess","Lorem Ipsum","9.99","2","2","6","1","60"), 
("2","Checkers","Lorem Ipsum","4.99","2","2","6","1","30"), 
("3","Catan","Lorem Ipsum","29.99","3","4","10","1","90"),
("4","Pandemic Legacy: Season 1","Pandemic Legacy is a co-operative campaign game, with an overarching story-arc played through 12-24 sessions, depending on how well your group does at the game.","69.99","2","4","13","1","60"), 
("5","Through the Ages: A New Story of Civilization","Through the Ages is a civilization building game. Each player attempts to build the best civilization through careful resource management, discovering new technologies, electing the right leaders, building wonders and maintaining a strong military.","59.95","2","4","14","1","180"), 
("6","The Jungle Book","Mowgli, as you know, must leave the Cave and return to the Man Village, accompanied by some of his jungle friends to see him safely on his way. So they decide to make a ""race"" of it, to see who can be the first to reach the Man Village.","19.95","2","4","6","2","20"), 
("7","1 2 3 Game","A great way to have fun learning numbers!","10.00","1","4","3","2","15"), 
("8","Cards Against Humanity","A party game for horrible people.","25.00","4","30","17","3","30"), 
("9","20 Questions","20 Questions is the popular panel game in which the panel ask up to 20 Questions to guess the Person, Place or Thing.","23.00","2","7","8","3","30"), 
("10",".hack//ENEMY","Confront the world of .hack. It will test you, captivate you, and engulf you... but dont let it destroy you. ","20.00","2","2","12","4","30"), 
("11","Joking Hazard","From the creators of Cyanide & Happiness comes a card game where players compete to finish an awful comic strip.","25.00","3","10","18","4","30"), 
("12","$ Fever","The goal is to achieve more winning combinations after 1 or more shots.","14.95","2","6","8","5","20"), 
("13","4 the Birds","4 the Birds is the board game in which you will use beak-and-taloned strategy as well as a peck of luck to be the first to ""flock"" four of your birds together in a tree besieged by a menagerie of other birds trying to do the same.","30.00","2","6","8","5","20"),
("14","The Shared Dream","Of Dreams and Magic: The Shared Dream is a cooperative board game for 2-4 players.","65.00","2","4","13","6","120"),
("15","The 7th Continent","Its the early 20th century. You have decided to sail back to the newly discovered seventh continent to attempt to lift the terrible curse that has struck you since your return from the previous expedition.","59.95","1","4","12","6","120"), 
("16","Abduction","The players take the role of victims of an alien abduction trying to escape from captivity on an alien ship. The object is to be the first to escape...","10.00","2","4","10","6","20"), 
("17","Terra Mystica","In the land of Terra Mystica dwell 14 different peoples in seven landscapes, and each group is bound to its own home environment, so to develop and grow, they must terraform neighboring landscapes into their home environments in competition with the other groups.","79.99","2","5","12","7","150"), 
("18","Caverna: The Cave Farmers","Caverna: The Cave Farmers is a worker-placement game at heart, with a focus on farming. In the game, you are the bearded leader of a small dwarf family that lives in a little cave in the mountains.","97.00","1","7","12","7","210"), 
("19","Mage Knight Board Game","The Mage Knight board game puts you in control of one of four powerful Mage Knights as you explore (and conquer) a corner of the Mage Knight universe under the control of the Atlantean Empire.","89.99","1","4","14","7","150"), 
("20","Scythe","It is a time of unrest in 1920s Europa. The ashes from the first great war still darken the snow. The capitalistic city-state known simply as “The Factory”, which fueled the war with heavily armored mechs, has closed its doors, drawing the attention of several nearby countries.","80.00","1","5","14","8","115"), 
("21","Star Wars: Imperial Assault","Star Wars: Imperial Assault is a strategy board game of tactical combat and missions for two to five players, offering two distinct games of battle and adventure in the Star Wars universe!","99.99","2","5","14","8","120"), 
("22","Blood Rage","For a Viking there are many pathways to glory. You can invade and pillage the land for its rewards, crush your opponents in epic battles, fulfill quests, increase your clans stats, or even die gloriously either in battle or from Ragnarök, the ultimate inescapable doom.","79.99","2","4","14","8","90"), 
("23","Mansions of Madness: Second Edition i","Mansions of Madness: Second Edition is a fully cooperative, app-driven board game of horror and mystery for one to five players that takes place in the same universe as Eldritch Horror and Elder Sign. Let the immersive app guide you through the veiled streets of Innsmouth and the haunted corridors of Arkhams cursed mansions as you search for answers and respite.","99.95","1","5","14","9","180"), 
("24","Dead of Winter","Dead of Winter: A Crossroads Game, the first game in this series, puts 2-5 players in a small, weakened colony of survivors in a world where most of humanity is either dead or diseased, flesh-craving monsters. Each player leads a faction of survivors with dozens of different characters in the game.","59.99","2","5","14","9","120"), 
("25","Eldritch Horror","Across the globe, ancient evil is stirring. Now, you and your trusted circle of colleagues must travel around the world, working against all odds to hold back the approaching horror.","59.99","1","8","14","9","240"), 
("26","Kingdon Death: Monster","Kingdom Death: Monster is a fully cooperative tabletop hobby game experience. Set in a unique nightmarish world devoid of most natural resources, you control a settlement at the dawn of its existence.","100.00","1","6","17","10","60"), 
("27","Tanto Cuore","Each player plays as the Lord of a mansion and hires maids to fill out their house to become the King of Maids! The end goal is simple enough, the player who has the most Victory Points at the end of the game wins!","49.95","2","4","13","10","45"), 
("28","Funny Friends","Each player plays a character who starts the game as a teenager and then must choose the cards that will make his life take shape.","39.00","2","6","16","10","60"), 
("29","Hanabi","A cooperative game in which players try to create the perfect fireworks show by placing the cards on the table in the right order.","8.00","2","5","8","11","25"), 
("30","Witness","Witness is set in the world of Blake and Mortimer, a Belgian comic series started in the 1940s by writer/artist Edgar P. Jacobs. In the game, which is playable strictly by four players, you each represent one of four characters and your goal is to solve mysteries or crimes by sharing information with one another — but you are quite restricted in how you can share information!","39.99","4","4","13","11","15"), 
("31","Pyramid","Fluch der Mumie (Curse of the Mummy) is a game with asymmetrical goals. While one player as the Mummy tries to catch tomb raiders, the other players try to secure as many treasures as possible from the Pyramid.","60.00","2","5","8","11","35"), 
("32","Le Havre","n Le Havre, a player’s turn consists of two parts: First, distribute newly supplied goods onto the offer spaces; then take an action","69.99","1","5","12","12","150"), 
("33","Keyflower","Keyflower is a game for two to six players played over four rounds. Each round represents a season: spring, summer, autumn, and finally winter.","72.99","2","6","12","12","120"), 
("34","Concordia","Two thousand years ago, the Roman Empire ruled the lands around the Mediterranean Sea. With peace at the borders, harmony inside the provinces, uniform law, and a common currency, the economy thrived and gave rise to mighty Roman dynasties as they expanded throughout the numerous cities.","64.99","2","5","13","12","100"), 
("35","War of the Ring","n War of the Ring, one player takes control of the Free Peoples (FP), the other player controls Shadow Armies (SA). Initially, the Free People Nations are reluctant to take arms against Sauron, so they must be attacked by Sauron or persuaded by Gandalf or other Companions, before they start to fight properly: this is represented by the Political Track, which shows if a Nation is ready to fight in the War of the Ring or not.","62.45","2","4","13","13","180"), 
("36","Robinsono Crusoe: Adventures on the Cursed Island","Robinson Crusoe: Adventures on the Cursed Island is a game created by Ignacy Trzewiczek, the author of Stronghold.","74.99","1","4","14","13","180"), 
("37","Arkham Horror: The Card Game","Something evil stirs in Arkham, and only you can stop it. Blurring the traditional lines between roleplaying and card game experiences, Arkham Horror: The Card Game is a Living Card Game of Lovecraftian mystery, monsters, and madness!","39.95","1","2","14","13","120"), 
("38","Sherlock Holmes Consulting Detective","Have you ever had the desire to walk the streets of Victorian London with Sherlock Holmes in search of Professor Moriarty? To search the docks for the giant rat of Sumatra? To walk up Baker Street as the fog is rolling in and hear Holmes cry out, ""Come, Watson, come! The game is afoot!""? Now you can!","70.0","1","8","10","14","120"), 
("39","Letters from Whitechapel","Get ready to enter the poor and dreary Whitechapel district in London 1888 – the scene of the mysterious Jack the Ripper murders","41.99","2","6","13","14","120"), 
("40","Mr. Jack","n Mr. Jack, one of the two players represents Jack the Ripper, who will be one of the eight characters on the board. This player knows which character is Mr. Jack, and his goal is to flee from the district as soon as possible (or avoid being accused for eight turns). ","42.99","2","2","9","14","30"), 
("41","Terraforming Mars","In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable.","69.95","1","5","12","15","120"), 
("42","Eclipse","The galaxy has been a peaceful place for many years. After the ruthless Terran–Hegemony War (30.027–33.364), much effort has been employed by all major spacefaring species to prevent the terrifying events from repeating themselves.","99.00","2","6","14","15","200"), 
("43","Android: Netrunner","Welcome to New Angeles, home of the Beanstalk. From our branch offices in this monument of human achievement, NBN proudly broadcasts all your favorite media programming.","39.95","2","2","14","15","45"), 
("44","Puerto Rico","In Puerto Rico players assume the roles of colonial governors on the island of Puerto Rico. The aim of the game is to amass victory points by shipping goods to Europe or by constructing buildings.","21.42","2","5","14","16","150"), 
("45","Agricola","In Agricola, youre a farmer in a wooden shack with your spouse and little else.","69.99","1","5","12","16","120"), 
("46","Power Grid","The objective of Power Grid is to supply the most cities with power when someones network gains a predetermined size. In this new edition, players mark pre-existing routes between cities for connection, and then bid against each other to purchase the power plants that they use to power their cities.","44.99","2","6","12","16","120"), 
("47","Fields of Arle","In the worker placement game Fields of Arle, set in the German region of East Frisia, players develop an estate and expand their territory by cutting peat and building dikes.","79.99","1","2","13","17","120"), 
("48","Goa","Goa, a strategy game of auctions and resource management, is set at the start of the 16th century: beautiful beaches, a mild climate, and one of the most important trading centers in the world.","97.9","2","4","12","17","90"), 
("49","Village","Life in the village is hard – but life here also allows the inhabitants to grow and prosper as they please. One villager might want to become a friar. Another might feel ambitious and strive for a career in public office. A third one might want to seek his luck in distant lands.","49.99","2","4","12","17","90"), 
("50","Galaxy Trucker","In a galaxy far, far away... they need sewer systems, too. Corporation Incorporated builds them. Everyone knows their drivers -- the brave men and women who fear no danger and would, if the pay was good enough, even fly through Hell.","59.95","2","4","10","18","60"), 
("51","Dixit Odyssey","Game play in Dixit Odyssey matches that of Dixit: Each turn one player is the storyteller. This player secretly chooses one card in his hand, then gives a word or sentence to describe this card—but not too obviously.","43.76","3","12","8","18","30"), 
("52","Dungeon Lords","n Dungeon Lords, you are an evil dungeonlord who is trying to build the best dungeon out there. You hire monsters, build rooms, buy traps and defeat the do-gooders who wish to bring you down.","69.95","2","4","12","18","90"), 
("53","Sleeping Queens","Rise and shine! The Pancake Queen, the Ladybug Queen, and ten of their closest friends have fallen under a sleeping spell and its your job to wake them up","9.99","2","5","8","19","10"), 
("54","Utopia Engine","Utopia Engine is a free print-and-play dice game for one player. You play an old artificer named Isodoros who is attempting to reconstruct the Utopia Engine, a fabled device from the distant past and possibly the only hope for averting the fast approaching Doomsday.","0.0","1","1","12","19","60"), 
("55","BuyWord","BuyWord is a game of words with a twist. You pay good hard cash to buy your letters, then form a word to sell at a profit, if you can.","14.99","1","4","8","19","45"), 
("56","Opera","n 1607 Monteverdi’s Opera La Favola d’Orfeo had its worldwide premiere. Over the following centuries, Europe was taken over. In the board game Opera, the players bring Opera to the public.","58.19","2","4","12","20","90"), 
("57","Rock the Beat","Players in Rock the Beat do just that, creating a steady beat by slapping their thighs and clapping their hands to the rhythm of the Queen song ""We Will Rock You"".","15.0","4","12","8","20","30"), 
("58","Schrille Stille","Players are the heads of 1 of 6 fictitious music companies, trying to predict/influence the popularity of 14 different musical acts.","15.00","3","6","10","20","60"), 
("59","Patchwork","In Patchwork, two players compete to build the most aesthetic (and high-scoring) patchwork quilt on a personal 9x9 game board. To start play, lay out all of the patches at random in a circle and place a marker directly clockwise of the 2-1 patch.","27.99","2","2","8","21","30"), 
("60","A Feast for Odin","Using the central board in A Feast for Odin, players have to hunt, gather basic materials, refine those materials, develop their production-buildings, build/buy ships, and raid settlements.","99.99","1","4","12","21","120"), 
("61","Legends of Andor","Legends of Andor is a cooperative adventure board game for two to four players in which a band of heroes must work together to defend a fantasy realm from invading hordes.","59.99","2","4","14","21","90"), 
("62","Zombiecide: Black Plague","Zombicide: Black Plague takes the zombie apocalypse into a fantastical medieval setting! The arcane powers of the Necromancers have unleashed a zombie invasion in the age of swords and sorcery, and its up to your group of straggling survivors to not only stay alive during these dark times, but to take back the realm and punish those responsible for the apocalypse!","99.99","1","6","10","22","180"), 
("63","Earth Reborn","arth Reborn offers nine scenarios that take you through missions of rescue, retrieval, and escort through areas of labs, mansions, towns, and more.","79.99","2","4","13","22","180"), 
("64","Last Night on Earth: The Zombie Game","Last Night on Earth, The Zombie Game is a survival horror board game that pits small-town Heroes head-to-head against a horde of Zombies.","59.99","2","6","12","22","90"), 
("65","Twilight Struggle","In 1945, unlikely allies toppled Hitlers war machine, while humanitys most devastating weapons forced the Japanese Empire to its knees in a storm of fire. Where once there stood many great powers, there then stood only two.","37.95","2","2","13","23","180"), 
("66","A Game of Thrones: The Board Game","n the second edition of A Game of Thrones: The Board Game, three to six players take on the roles of the great Houses of the Seven Kingdoms of Westeros, as they vie for control of the Iron Throne through the use of diplomacy and warfare.","59.99","3","6","14","23","240"), 
("67","Paths of Glory","They called it the Great War. In over four years of titanic struggle, the ancient Europe of Kings and Emperors tore itself to pieces, giving birth to our own violent modern age.","49.95","2","2","14","23","480"), 
("68","Wits & Wagers","Not a trivia buff? It doesnt matter! In Wits & Wagers, each player writes a guess to a question such as “In what year did the bikini swimsuit makes its first appearance?” or “How many feet wide is an NFL football field?” and places it face-up on the betting mat.","34.99","3","7","10","24","25"), 
("69","Timeline: Inventions","Timeline: Inventions is a card game played using 109 cards. Each card depicts an invention on both sides, with the year in which that invention was created on only one side.","14.99","2","8","8","24","15"), 
("70","Timeline: Historical Events","Timeline: Events is a card game played using 110 cards. Each card depicts a historical event on both sides, with the year in which that event occurred on only one side.","14.99","2","8","8","24","15"), 
("71","1775: Rebellion","In 1775: Rebellion, players take the roles of the American Continental Army and Patriots against the British Army and the Loyalists. Each side tries to control the colonies, provinces and territories.","70.00","2","4","10","25","120"), 
("72","Freedom: The Underground Railroad","Early in the history of the United States, slavery was an institution that seemed unmovable but with efforts of men and women across the country, it was toppled. In Freedom: The Underground Railroad, players are working to build up the strength of the Abolitionist movement through the use of notable figures and pivotal events. By raising support for the cause and moving slaves to freedom in Canada, the minds of Americans can be changed and the institution of slavery can be brought down.","69.99","1","4","13","25","120"), 
("73","Evolution","In Evolution, players adapt their species in a dynamic ecosystem where food is scarce and predators lurk. Traits like Hard Shell and Horns will protect your species from Carnivores, while a Long Neck will help them get food that others cannot reach. With over 4,000 ways to evolve your species, every game becomes a different adventure.","54.99","2","6","12","25","70"), 
("74","Exploding Kittens","Players draw cards until someone draws an Exploding Kitten, at which point they explode, they are dead, and they are out of the game.","19.99","2","4","13","4","30");
';

DB::select(DB::raw($sql));
    }
}
